name: Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  prepare-release-on-servers:
    name: "Prepare release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: p630962.mittwaldserver.info
          username: p630962
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: test.txt
          target: /files/test
